version: "3.9"
   
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: "search_gkh"
      POSTGRES_USER: "artur"
      POSTGRES_PASSWORD: "1234"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d search_gkh -U artur"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'